#! /bin/sh
echo "Version: "
read g
f="./DEB/DEBIAN/control"
echo "Setting version to $g in $f"
echo "Package: com.phyrrus9.sks3" >> $f
echo "Maintainer: Ethan Laur (phyrrus9)" >> $f
echo "Architecture: all" >> $f
echo "Description: Console based DND game for mac os x" >> $f
echo "Version: $g" >> $f
echo "Section: Games" >> $f
echo "Homepage: http://github.com/phyrrus9/SKS3" >> $f
